install:
  - set PATH=C:\Ruby23\bin;%PATH%
  - bundle install

init:
  - git config --global core.autocrlf true

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake

# Don't double-build PRs
skip_branch_with_pr: true

build: off
