version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\Originate\git-town

environment:
  GOPATH: c:\gopath

init:
  - git config --global core.autocrlf true

install:
  - set PATH=%GOPATH%\bin;%PATH%
  - go version
  - go get github.com/Masterminds/glide
  - glide install
  - set PATH=C:\Ruby23\bin;%PATH%
  - bundle install

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec cucumber features

# Don't double-build PRs
skip_branch_with_pr: true

build: off
deploy: off
